### ISSUE TITLE
Problem: SS locations are not created during bootstrap

### ISSUE THREAD

**Issue by sevein** [JiscRDSS/rdss-archivematica#168] opened 2018-01-04 23:08 UTC
After running `make bootstrap` my Storage Service only shows three locations: currently processing and the automated/interactive transfer sources. Running `make -C dev/ bootstrap-storage-service bootstrap-dashboard` or `make -C dev/ bootstrap-dashboard` doesn't solve the problem.

This is blocking me from doing development work.

**Comment by sevein** [comment] 2018-01-05 00:07
When running the following:

```
docker-compose -f docker-compose.qa.yml -f docker-compose.dev.yml run \
    --rm \
    --entrypoint /src/dashboard/src/manage.py \
      archivematica-dashboard \
        install \
          --username="test" \
          --password="test" \
          --email="test@test.com" \
          --org-name="test" \
          --org-id="test" \
          --api-key="test" \
          --ss-url="http://archivematica-storage-service:8000" \
          --ss-user="test" \
          --ss-api-key="test"
```

I was consistently seeing something like the following in the SS logs:

```
Creating default locations for pipeline Archivematica on 5ab80adf1b32 (c4c14bc3-9c68-4b11-b766-2f59d5950010).
Currently processing: 6c90e973-47e6-4cec-9e56-dba41af2a0af: var/archivematica/sharedDirectory/ (Currently Processing)
```

For unknown reasons, after restart `archivematica-storage-service` the problem is solved. Now what I see is:

```
Creating default locations for pipeline Archivematica on 5ab80adf1b32 (c4c14bc3-9c68-4b11-b766-2f59d5950010).
Currently processing: 6c90e973-47e6-4cec-9e56-dba41af2a0af: var/archivematica/sharedDirectory/ (Currently Processing)
Adding new AS cd358e85-faca-4d8f-a6be-6d6552c35485: var/archivematica/sharedDirectory/www/AIPsStore (AIP Storage) to Archivematica on 5ab80adf1b32 (c4c14bc3-9c68-4b11-b766-2f59d5950010)
Adding new DS 8a9f5c79-ee0d-44d5-945d-2bb0a5b096e2: var/archivematica/sharedDirectory/www/DIPsStore (DIP Storage) to Archivematica on 5ab80adf1b32 (c4c14bc3-9c68-4b11-b766-2f59d5950010)
Adding new BL 4d0d7171-5803-4fa9-a259-a1d9dea207af: var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog (Transfer Backlog) to Archivematica on 5ab80adf1b32 (c4c14bc3-9c68-4b11-b766-2f59d5950010)
Adding new AR d40b9549-d24a-4d08-9f3a-d7c9bf96ed38: var/archivematica/storage_service/recover (AIP Recovery) to Archivematica on 5ab80adf1b32 (c4c14bc3-9c68-4b11-b766-2f59d5950010)
```

**Comment by sevein** [comment] 2018-01-05 00:24
When I executed the following command the problem came back:

    $ make -C dev bootstrap-storage-service bootstrap-dashboard restart-mcp-services ENV=dev

I only restarted `archivematica-storage-service` and reloaded `http://0.0.0.0:32827/locations/` and now I see the missing locations but they don't have a pipeline assigned.

**Comment by mamedin** [comment] 2018-01-05 13:58
When running the bootstrap-storage-service without a container reboot, the `Administration>Settings` tab shows no default locations configured. But after restarting the storage-service container this settings looks good.

The issue is fixed adding at the end of the `bootstrap-storage-service`:

```
docker-compose restart archivematica-storage-service
```

**Comment by sevein** [comment] 2018-01-22 23:38
I've started to suspect that this is related to the [`startup() function`](https://github.com/artefactual/archivematica-storage-service/blob/e91aeb8aa06ca9775915e79ddda617bd0d160044/storage_service/storage_service/urls.py#L48-L141) which is executed when you restart SS.

It seems that `make bootstrap ENV=dev` doesn't succeed unless that function is executed.

I think that startup() should be deleted and https://github.com/artefactual/archivematica-storage-service/blob/stable/0.11.x/storage_service/locations/models/pipeline.py#L91-L159 should be updated so it can populate the locations without any previous state.

**Comment by jhsimpson** [comment] 2018-01-23 00:00
I agree that the startup() function should be deleted.  I am not sure I understand the change you are proposing to https://github.com/artefactual/archivematica-storage-service/blob/stable/0.11.x/storage_service/locations/models/pipeline.py#L91-L159 though.  Can you explain a bit more?

**Comment by sevein** [comment] 2018-01-23 00:08
I haven't digged to dip into it but if you look at `startup()` it seems to be storing the locations of the UUIDs in the database (settings table). That's later used by `create_default_locations()`. If they're missing the corresponding LocationPipeline objects will not be created.

**Comment by jhsimpson** [comment] 2018-01-23 00:20
I see.  Ok, I agree, Do you want to take assignment of this issue, or perhaps assign to @helenst  to work on ?

**Comment by sevein** [comment] 2018-01-23 00:23
I'll do it tomorrow!

**Comment by sevein** [comment] 2018-01-24 16:14
I've filed an issue in the SS repo with some extra thoughts about it, see [#303](https://github.com/artefactual/archivematica-storage-service/issues/303). In vanillla's Compose environment, the workaround was to restart SS right after `manage.py migrate` is executed ([e9e191926](https://github.com/artefactual-labs/am/commit/e9e1919261341220c5a71b48144fde6a8d8e3808)).

**Closed** 2018-07-07 15:20 UTC
Labels: dev
