### ISSUE TITLE
Problem: Appraisal Tab: Analysis and Arrangement panes not working

### ISSUE THREAD

**Issue by mjaddis** [JiscRDSS/rdss-archivematica#41] opened 2017-06-23 07:44 UTC
I used the QA env and did a transfer for some of the Artefactual sample dataset (images) and sent to backlog.  The Analysis pane in the Appraisal tab shows nothing - no file format information, no previews etc.  It is also not possible to drag folders from the Backlog pane to the Arrangement pane in order to build a SIP.  I tried the community release of Archivematica 1.6 in the same web browser I used for this test (Chrome) and it worked fine, so doesn't look like a browser issue per se.

I tailed the logs at and saw the errow below when first entering the Appraisal Tab.  

```
archivematica-dashboard_1                       | Internal Server Error: /access/archivesspace/levels/
archivematica-dashboard_1                       | Traceback (most recent call last):
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
archivematica-dashboard_1                       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
archivematica-dashboard_1                       |   File "/src/dashboard/src/components/access/views.py", line 48, in wrapper
archivematica-dashboard_1                       |     client = _get_client_by_type(system)
archivematica-dashboard_1                       |   File "/src/dashboard/src/components/access/views.py", line 35, in _get_client_by_type
archivematica-dashboard_1                       |     return get_as_system_client()
archivematica-dashboard_1                       |   File "/src/dashboard/src/components/ingest/views_as.py", line 27, in get_as_system_client
archivematica-dashboard_1                       |     repository=config['repository']
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/agentarchives/archivesspace/client.py", line 61, in __init__
archivematica-dashboard_1                       |     self._login()
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/agentarchives/archivesspace/client.py", line 65, in _login
archivematica-dashboard_1                       |     response = requests.post(self.host + '/users/' + self.user + '/login', data={'password': self.passwd, 'expiring': False}, timeout=self.timeout)
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 109, in post
archivematica-dashboard_1                       |     return request('post', url, data=data, json=json, **kwargs)
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
archivematica-dashboard_1                       |     response = session.request(method=method, url=url, **kwargs)
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 451, in request
archivematica-dashboard_1                       |     prep = self.prepare_request(req)
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 382, in prepare_request
archivematica-dashboard_1                       |     hooks=merge_hooks(request.hooks, self.hooks),
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 304, in prepare
archivematica-dashboard_1                       |     self.prepare_url(url, params)
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 365, in prepare_url
archivematica-dashboard_1                       |     raise InvalidURL("Invalid URL %r: No host supplied" % url)
archivematica-dashboard_1                       | InvalidURL: Invalid URL u'http://:8089/users//login': No host supplied
archivematica-dashboard_1                       | ERROR     2017-06-23 07:25:03  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /access/archivesspace/levels/
archivematica-dashboard_1                       | Traceback (most recent call last):
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
archivematica-dashboard_1                       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
archivematica-dashboard_1                       |   File "/src/dashboard/src/components/access/views.py", line 48, in wrapper
archivematica-dashboard_1                       |     client = _get_client_by_type(system)
archivematica-dashboard_1                       |   File "/src/dashboard/src/components/access/views.py", line 35, in _get_client_by_type
archivematica-dashboard_1                       |     return get_as_system_client()
archivematica-dashboard_1                       |   File "/src/dashboard/src/components/ingest/views_as.py", line 27, in get_as_system_client
archivematica-dashboard_1                       |     repository=config['repository']
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/agentarchives/archivesspace/client.py", line 61, in __init__
archivematica-dashboard_1                       |     self._login()
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/agentarchives/archivesspace/client.py", line 65, in _login
archivematica-dashboard_1                       |     response = requests.post(self.host + '/users/' + self.user + '/login', data={'password': self.passwd, 'expiring': False}, timeout=self.timeout)
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 109, in post
archivematica-dashboard_1                       |     return request('post', url, data=data, json=json, **kwargs)
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
archivematica-dashboard_1                       |     response = session.request(method=method, url=url, **kwargs)
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 451, in request
archivematica-dashboard_1                       |     prep = self.prepare_request(req)
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 382, in prepare_request
archivematica-dashboard_1                       |     hooks=merge_hooks(request.hooks, self.hooks),
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 304, in prepare
archivematica-dashboard_1                       |     self.prepare_url(url, params)
archivematica-dashboard_1                       |   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 365, in prepare_url
archivematica-dashboard_1                       |     raise InvalidURL("Invalid URL %r: No host supplied" % url)
archivematica-dashboard_1                       | InvalidURL: Invalid URL u'http://:8089/users//login': No host supplied
```

![screen shot 2017-06-23 at 08 35 06 2](https://user-images.githubusercontent.com/25819534/27471521-de8d9906-57ef-11e7-9927-fd216bbeaabb.png)

**Comment by jrwdunham** [comment] 2017-09-18 16:22
I spent some time looking into this. I think at least part of the problem is that the appraisal_tab.js build in this repo does not include the changes from https://github.com/artefactual-labs/appraisal-tab/pull/159 which fix jQueryUI dependency mismatches, which are causing the `draggable is not a function` errors viewable from the JS console.

**Comment by mjaddis** [comment] 2017-10-03 08:21
Corresponding JIRA issue: https://jiscdev.atlassian.net/browse/RDSSARK-229

**Comment by joel-simpson** [comment] 2017-12-21 02:04
This issue was fixed by https://github.com/JiscRDSS/archivematica/pull/47 and 
https://github.com/JiscRDSS/rdss-archivematica/pull/123
Test results noted in rdssark-229

**Closed by joel-simpson** 2017-12-21 02:04 UTC
